# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

title: so' blog
author: so
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fantasie.github.io" # the base hostname & protocol for your site
description: "http://so-blog.net <i class='fa fa-heart'></i> My Personal Repository"
github_username:  fantasie
excerpt_separator: "<!-- more -->"
auto: true # automatically update your jekyll
server: true # runs a local server
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
#gems: [jekyll-paginate, jekyll-paginate-category]
permalink: /:year/:month/:day/:title/
comments:
  url: "http://ec2-52-79-127-116.ap-northeast-2.compute.amazonaws.com:7000/jekyll-discuss/comments"

paginate: 10
blog_pagenate: 1
diary_pagenate:	5
tag_pagenate: 10

paginate_path: "page:num"

categories: ["blog","diary"]

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
